services:
  web:
    image: httpd
    port: http:80
workflows:
  change:
    create:
      - test: staging
      - deploy: staging/httpd-$branch
    update:
      - test: staging
      - deploy: staging/httpd-$branch
    close:
      - delete: staging/httpd-$branch
  merge:
    master:
      - create: staging/httpd-staging
      - deploy: staging/httpd-staging
